# This workflow will run tests and lint with a single version of Python

name: AirBnB clone

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8.5"
    - name: Install pycodestyle
      run: pip install pycodestyle==2.8.*
    - name: Lint with pycodestyle
      run: |
        pycodestyle .
    - name: Test with unittest
      run: |
        python3 -m unittest discover tests
